### ISSUE TITLE
Youtube launch link

### ISSUE THREAD

**Issue by forinda** [alphaolomi/alphaolomi.com#53]
Could you make the link open up in a new tab and not navigate you outside your portfolio website

**Comment by alphaolomi** [comment]
Thank you 🤝  @forinda

**Comment by forinda** [comment]
Sounds good. Good work @alphaolomi I'm also building my react js skills :smile:

**Comment by alphaolomi** [comment]
Best of luck, Feel free to tag me along the way, Looking forward on seeing your React projects.

**Comment by forinda** [comment]
Sure
